server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: rotas como /5off/<codigo> devem cair no index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:mp4|png|jpg|jpeg|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    location ~* \.(?:css|js)$ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
        try_files $uri =404;
    }
}
